SUBCOMMANDS = subcommands/report subcommands/set
TRIGGERS = triggers/check-deploy triggers/core-post-deploy triggers/install triggers/post-app-clone-setup triggers/post-app-rename-setup triggers/post-create triggers/post-delete triggers/pre-deploy triggers/pre-restore triggers/scheduler-app-status triggers/scheduler-deploy triggers/scheduler-enter triggers/scheduler-inspect triggers/scheduler-is-deployed triggers/scheduler-logs triggers/scheduler-logs-failed triggers/scheduler-register-retired triggers/scheduler-retire triggers/scheduler-run triggers/scheduler-run-list triggers/scheduler-stop
BUILD = commands subcommands triggers
PLUGIN_NAME = scheduler-docker-local

include ../../common.mk
